### ISSUE TITLE
input user volume not used for fs creation

### ISSUE THREAD

**Issue by andreworg** [ackoujens/archlinux-raspberry-pi-2-install#1]
the script inputs the name of the volume in the $uservolume var, then uses it for partitioning but not for fs creation (the code statically references /dev/sdb1 and /dev/sdb2).

**Comment by ackoujens** [comment]
Thanks @andreworg. Sure was not what I intended. I'll fix it right away.

**Comment by ackoujens** [comment]
Just pushed a fix. Also looked at echoing the input variable. Thanks for the issue report @andreworg!
